### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by tbm** [UniversalDependencies/UD_Swahili-OPUSGV#1]
> * 2021-05-15 v2.8
>  * Initial release in Universal Dependencies.

Version 2.9 is out but doesn't have Swahili.

Can you post an update or a link where I can read about the status?

Thanks

**Comment by tbm** [comment]
Is there any update on this?

**Comment by dan-zeman** [comment]
@ksteimel

**Comment by ksteimel** [comment]
Hi @tbm. This is not yet ready for release. Thank you for the interest though.

**Comment by lordrobbiel** [comment]
Hi, I am also interested

**Comment by tbm** [comment]
@ksteimel just wanted to ask if you're still working on this and if there's a new ETA. Thanks!

**Comment by ksteimel** [comment]
I am still working on this but there is no new ETA.

**Comment by tbm** [comment]
For others looking, it seems the work is in https://git.steimel.info/ksteimel/SWH_UDT

See this paper: https://aclanthology.org/2023.rail-1.10.pdf
